[package]
name = "tokio-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version = "1", features = ["full"]}
dotenv = "0.15.0"
thiserror = "1.0.31"
colored = "2.0.0"